### ISSUE TITLE
Deal with the duplicate port names and rerun everything.  

### ISSUE THREAD

**Issue by fredtal** [kaycole/fish_shift#52]
There are 8 duplicate port names: Freeport (NY, ME), Hampton (VA, NH), Ocean City (NJ, MD), Portland (CT, ME), Portsmouth (NH, RI), Rockport (ME, MA), Stonington (ME, CT), Westport (CT, ME, MA).  When we created the communities, I think we just used port name, so probably Rockport, ME and Rockport, MA are currently being treated as a single community (ha).  So we have to fix that.  

@emfuller and @kaycole, we should probably just do this in the clean version of the code.

**Comment by emfuller** [comment]
now `portlnd1` is `port, state`. 

this code is in `fish_shift/Code/species_data_code`
