### ISSUE TITLE
Incorporate `home port` and `decport` into definitions of community

### ISSUE THREAD

**Issue by emfuller** [kaycole/fish_shift#53]
Right now don't have the permit data. Once we get this, adjust `2_perport.R` to also include home port and declared ports.

**Comment by emfuller** [comment]
And need to not use opernum as the vessel identifier.

**Comment by kstmarti** [comment]
I don't think we use opernum for anything. The vessel ID number is VPNUM or similar. Yes?
Kevin

**Comment by emfuller** [comment]
Yep, agreed. This was a note to myself to correct the code. :)
