### ISSUE TITLE
triplength > 364?

### ISSUE THREAD

**Issue by fredtal** [kaycole/fish_shift#56]
Right now, treat_data removes all trips > 364 days.  Wasn't there some thing earlier that trips > 364 were probably ones that left in Dec and came back in Jan?  I seem to remember this but don't remember how/if we dealt with it.

**Comment by emfuller** [comment]
Yeah,  I can't remember either. But do you see any trips with that length? I was just playing around with `treat_data.R`, and don't see any. The longest I see is 62 days (2 months). That looks wrong, and it looks like that trip caught a tiny amount of fish. So is maybe a day trip?

I do, however, see crew with values as high as 70. I plotted them up, and there's a ton of outlier-looking crew values. Only after crew is below 16 do we start to see substantial numbers of trips. 

In general, maybe we need to remember/review how Kevin "cleans" this data? 

The R code I was troubleshooting in will be pushed shortly.

**Comment by kstmarti** [comment]
Friends,

Yes, I had some "thresholds" related to crew size, trip length, quantity 
caught, etc. that removed those data which seemed well beyond any 
realistic measure. We could eliminate the trip or just the data point... 
Perhaps we can talk about this and set these thresholds at our meeting? 
Or maybe I have what I used in the past somewhere... I will look? Or 
maybe we should remove outliers statistically?

Cheers,
Kevin

**Comment by fredtal** [comment]
Okay, all good to know and think about.  I'm a bit buried in this code so don't have thoughts yet on what I think we should do, but certainly we can talk next week.  

Also the trip_days column (which appears to have come with the data) is different from the days column that we calculate from datelnd1-datesail.  I checked, and for some (but not all) trips with days > 1, trip_days appears to be one day longer than days, but there are no discrepancies larger than 1 day.  FYI.

**Comment by kstmarti** [comment]
I can't recall exactly why that is the case but I do recall some accommodation for the difference being equal to zero (when a trip begins and ends on the same day). I think that was 1 day... Indeed I think it made sense to calculate days as the difference plus 1 for all trips. I'll check to see where days comes from... 
Cheers,
Kevin

**Comment by emfuller** [comment]
Ha, I knew we had discussed this before. Current status is that we remove trips with crew > 20, and length > 100 days. There were a few negative trips (returning before they left), those dates were reversed. 

Crew with 0 or NA value were replaced with 1. Day length of 0 or NA were replaced by 1
