### ISSUE TITLE
same species recorded multiple times for single trip

### ISSUE THREAD

**Issue by mikprov** [kaycole/fish_shift#57]
In some communities (eg. lobster in Portland ME), lobster catch is recorded multiple times for a single trip. For example, in trip 1456700 lobster was entered twice: quantity kept is 327 for one entry and 47 in a second entry. 

I thought each trip should have one value (for quantity kept) per species, but I'm seeing multiple catch values for a single trip. Does this seem right?

(note: I'm not seeing this in every community)

**Comment by emfuller** [comment]
In my mind there are two possible sources of this error

1. This is in the VTR data itself
2. I introduce this in how I anonymize trips.

Kevin do you know if this exists in the raw VTR data?

**Comment by kstmarti** [comment]
Hmmm???? I really don't know... Species is by trip... but maybe they are 
in lots of some sort? That is, these are "hail weights" estimated by 
captains and maybe those estimations are for different classes within 
species (e.g. two different size lobsters which is not accounted for on 
the VTR form but would be how the captain accounts for them). I'm just 
guessing... Maybe looking at the VTR forms themselves (and the 
instructions for captains) would give us a clue... I think both can be 
found online.

Cheers,
Kevin

**Comment by emfuller** [comment]
For the record, that particular duplicate is in the raw data.

And upon further reflection, I think it makes sense.

Theoretically, each haul is supposed to have it's own dec lon/dec lat,
correct? So for a single trip there could be multiple entries for a species
(i.e. same species caught in two different hauls).

So I think summing the species before making your trip/species tables is
correct.

But this raises another issue: When I make a trip-id, I don't even check if
there are multiple locations per trip. I'll open a new issue for this and
check later today.

**Comment by kstmarti** [comment]
Okay. I just looked at the VTR instructions. Species is not by trip but 
by gear deployment.

Gear deployment is not haul (there can be multiple hauls in one gear 
deployment); it is when the vessel changes its gear. As a result, there 
could be multiple gear deployments per trip but there rarely is... For 
each gear deployment there are species caught and discarded and one 
location recorded.

So, species is not by trip (but is mostly)...

The older data we have that does not have species was pulled such that 
there was only one record per trip and hence one location (even when 
there are multiple gear deployments). The data we have by species has 
multiple records for each trip and maybe there are broken into gear 
deployments too...

Cheers,
Kevin

**Comment by fredtal** [comment]
Thanks for all of this.  It makes sense to me.

**Comment by emfuller** [comment]
Closing this, I think it's been resolved.
