### ISSUE TITLE
Check for multiple declon/declat for a single tripid

### ISSUE THREAD

**Issue by emfuller** [kaycole/fish_shift#58]
Possible that vessels actually do report multiple locations for a single trip. How does the current version of CaS handle this?

**Comment by emfuller** [comment]
It's the case that a single trip has more than one point. And if we assign fisher-days to each declon/declat, then we'll in a sense be double counting the fisher days. 

I am pondering the idea of: for all trips that have multiple declon/declats to divide the fisher days equally across them. So a trip with 24 fisher days with two locations will have 12 fisher days at each one.

**Comment by fredtal** [comment]
How many trips are we talking about here?

**Comment by emfuller** [comment]
30937 trips, or about 1.7% of total trips.
