### ISSUE TITLE
pdfs in loop not working yet

### ISSUE THREAD

**Issue by mikprov** [kaycole/fish_shift#60]
The nmds pdfs are not printing outside the loop yet.

**Comment by emfuller** [comment]
I think this is closed, since I see the pdfs

**Comment by mikprov** [comment]
Yep, thanks for closing.

On Sun, Mar 15, 2015 at 9:27 AM, Emma Fuller <notifications@github.com>
wrote:

> I think this is closed, since I see the pdfs
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kaycole/fish_shift/issues/60#issuecomment-81008309>.
>



-- 
Mikaela Provost
World Wildlife Fund
1250 24th St NW
Washington, DC 20090
