### ISSUE TITLE
Figure out why not all communities plots are printing

### ISSUE THREAD

**Issue by emfuller** [kaycole/fish_shift#61]

**Comment by mikprov** [comment]
Looks good now. Thank you!

On Sun, Mar 15, 2015 at 9:35 AM, Emma Fuller <notifications@github.com>
wrote:

> Closed #61 <https://github.com/kaycole/fish_shift/issues/61> via 2044dc8
> <https://github.com/kaycole/fish_shift/commit/2044dc83e1954959d99843aba3ef7f2260e403c4>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kaycole/fish_shift/issues/61#event-254447988>.
>



-- 
Mikaela Provost
World Wildlife Fund
1250 24th St NW
Washington, DC 20090
