### ISSUE TITLE
Where is portlat?

### ISSUE THREAD

**Issue by mikprov** [kaycole/fish_shift#64]
I want to sort communities by latitude in punchcard plots, where can I find lat? Talia, do you know?

**Comment by fredtal** [comment]
yes!  i have it, and thought i merged it but will add it.

**Comment by fredtal** [comment]
I just added a file to /nfs/fish-fishers-data called "CaS.commercial_all_port_land_wportloc.RDS" that includes columns for port lat and port lon if we have them from Kevin's list of ports.  @mikprov, if you can get a good looking punchcard plot before Fri I can put it in the EcoGSA talk Fri afternoon.
