### ISSUE TITLE
unable to view my .pdf files on GitHub?

### ISSUE THREAD

**Issue by mikprov** [kaycole/fish_shift#74]
Not sure what I am doing wrong, but I'm having trouble viewing the pdf files I push from R on the GitHub website. I see the file in the GitHub directory, but when I click on it nothing shows. Any thoughts? Most recent .pdf is Code/community_analysis/community_slope_vs_latitude_plot.pdf

**Comment by emfuller** [comment]
I don't think github previews PDFs. To see them I think you have to
download the "raw" version.
