### ISSUE TITLE
Need to calculate great circle distance for port_dist_from_bottom_trawl (along-shelf)

### ISSUE THREAD

**Issue by kaycole** [kaycole/fish_shift#75]
Need to add this is centroid calculation

**Comment by kaycole** [comment]
step 1: along_across_cluster_wrapper.R altered to now include port_lat, port_lon -> new cluster needs to be run. Talia wrote that this took 4 days on the SESYNC Rstudio so it'll probably be longer now

**Comment by kaycole** [comment]
Should we just use McSpatial, geodistance from the min. survey lat. to calculate along shelf distance (like Talia did in calc_dist_from_port.R) since we're only interested in the along shelf distance as a N/S indicator not the exact point? Talia I'm assuming this is a lot faster?

**Comment by kaycole** [comment]
step 2: added port_along to run_centroids (instead of in treat_data.R) ... will beed to test this once the new dataset is generated and make sure that there not two "1"'s and "2"s for both fishing and port along/across metrics

**Comment by kaycole** [comment]
step 3: added port_along into centroid.R in several spots

**Comment by fredtal** [comment]
Hey @emfuller, @kaycole  and I are wondering about whether we can use geodistance to calculate along shelf distance.  Is there anything with the curve of the earth that will cause problems with that?

**Comment by fredtal** [comment]
another suggestion from @kaycole to think about: a simple match with the along at lat data points, instead of the whole pick from points.  like closet point thing, where min(abs(a-b)).
