### ISSUE TITLE
some of the ports in Kevin's list don't have GPS locations

### ISSUE THREAD

**Issue by fredtal** [kaycole/fish_shift#77]
Right now, I'm just deleting them.  But it seems like it would be better to actually go through and add them to all the missing ports, yeah?

**Comment by emfuller** [comment]
working on this now, will re-calc lat/lon for all ports using google maps API. Then I'll quality check (compare to original lat/lon that kevin gave us, make a map of it of points) and then replace all with google maps versions (assuming they're good).

**Comment by mikprov** [comment]
Thanks for doing this!

On Fri, May 15, 2015 at 1:00 PM, Emma Fuller <notifications@github.com>
wrote:

> working on this now, will re-calc lat/lon for all ports using google maps
> API. Then I'll quality check (compare to original lat/lon that kevin gave
> us, make a map of it of points) and then replace all with google maps
> versions (assuming they're good).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kaycole/fish_shift/issues/77#issuecomment-102458964>.
>



-- 
Mikaela Provost
World Wildlife Fund
1250 24th St NW
Washington, DC 20090
