### ISSUE TITLE
update on delta_groundfish_comms

### ISSUE THREAD

**Issue by mikprov** [kaycole/fish_shift#80]
I copy & pasted the script for building the delta_groundfish_comms data frame in Talia's create_delta_groundfish_comms script. Feel free to improve and make changes. Right now I have slope(change in centroid lat/time) and the abs(slope(change in centroid lat/time)) as two columns in the data frame. Fleet size is mean community size over all years.

**Comment by fredtal** [comment]
Yay!  I added dist_from_port_slope, fleet_size_slope, shannon-wiener mean (across years) and shannon-wiener slope.  The table is saved at "/nfs/fish-fishers-data/delta_groundfish_comms.RDS".

**Comment by fredtal** [comment]
It's currently based on the old centroids file, since we're still working on regenerating the new centroids file.  @emfuller, hope you can work with that.  :/

**Comment by fredtal** [comment]
@mikprov I really liked your coding style in this!  Especially that one liner to extract the slope.  :)

**Comment by mikprov** [comment]
thanks @fredtal :)

**Comment by emfuller** [comment]
@fredtal, i see three files: `centroids2_old.RDS`, `centroids2.RDS`, and `centroids_old.RDS`, which one should I be using?

**Comment by emfuller** [comment]
oh wait, nm. I get it. I should be using `delta_groundfish_comms.RDS` which was generated from old centroids data, is that it?

**Comment by mikprov** [comment]
I think you're right @emfuller <https://github.com/emfuller>. Use
delta_groundfish_comms

On Mon, May 18, 2015 at 2:46 PM, Emma Fuller <notifications@github.com>
wrote:

> oh wait, nm. I get it. I should be using delta_groundfish_comms.RDS which
> was generated from old centroids data, is that it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kaycole/fish_shift/issues/80#issuecomment-103169470>.
>



-- 
Mikaela Provost
World Wildlife Fund
1250 24th St NW
Washington, DC 20090

**Comment by fredtal** [comment]
yeah.  but as soon as we have new centroids, we can rerun delta so it's
from the new data.  but you can start working with the current delta now.

On Mon, May 18, 2015 at 2:47 PM, mikprov <notifications@github.com> wrote:

> I think you're right @emfuller <https://github.com/emfuller>. Use
> delta_groundfish_comms
>
> On Mon, May 18, 2015 at 2:46 PM, Emma Fuller <notifications@github.com>
> wrote:
>
> > oh wait, nm. I get it. I should be using delta_groundfish_comms.RDS which
> > was generated from old centroids data, is that it?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/kaycole/fish_shift/issues/80#issuecomment-103169470
> >.
> >
>
>
>
> --
> Mikaela Provost
> World Wildlife Fund
> 1250 24th St NW
> Washington, DC 20090
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kaycole/fish_shift/issues/80#issuecomment-103169918>.
>



-- 
Talia Young
Graduate Program in Ecology & Evolution
Department of Marine and Coastal Sciences
Rutgers University
71 Dudley Road
New Brunswick, NJ 08901
tyoung@marine.rutgers.edu
http://marine.rutgers.edu/~tyoung/

**Comment by fredtal** [comment]
kaycee debugged and reran centroids.  (it needs some work still but the frame is good.)  i started generating a new delta_groundfish_comms but it barfed and i don't have time to debug it now.  i can do it tomorrow.  @emfuller, if you want one to work with in the meantime, you can still use <delta_groundfish_comms>, which was generated from the old centroids.

**Comment by fredtal** [comment]
okay, generated and saved new delta_groundfish_comms from new centroids.
