### ISSUE TITLE
Fix centroids

### ISSUE THREAD

**Issue by kaycole** [kaycole/fish_shift#81]
There are issues going on right now with centroids, I was trying to put in dummy variables right now to make it run but I wouldn't run it right now...

port_along is a dummy because not the right number of rows, might rerun this anyway with FNN library option

total_quantity is not coming up right, not sure what happened here...

will look into this, there are just zeros in the code where these variables were to help it run but theres also a loop error so i need to look into it when i get out of work or this weekend

**Comment by emfuller** [comment]
probably i'm meddling where I shouldn't be, but what's the `total_quantity` column? there was one of that name in Kevin's original data but I dropped it since it was something that he had calculated and not part of the original raw data.

**Comment by fredtal** [comment]
I removed total_quant and sd_quant.  port_along is fixed.
