### ISSUE TITLE
calc_dist_from_port.R not working

### ISSUE THREAD

**Issue by kaycole** [kaycole/fish_shift#84]
@fredtal  distfromport_km is not in CAS after this is run, distfromport_km is in centroids.R but not actually there

**Comment by emfuller** [comment]
not familiar with the centroid code. but i do this now in centroids and it should be passed in with new communities-at-sea data. you might need to change column names.

**Comment by fredtal** [comment]
we're now just calculating a mean from the dist_from_port in CaS!
